modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/ThePoultryMan/ARRP-But-Different/issues"
license = "GNU LGPL 3.0"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "ThePoultryMan"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${min_minecraft_version},${minecraft_upper_bound})"
ordering = "NONE"
side = "BOTH"

${test_mod_block}
